Simulation = "TournamentLottery"
Servers = 4
Bf = 9
Rounds = 1
RunWait =  "30000s"
Delay = 100
Bandwidth = 100
Suite = "Ed25519"

Hosts, NumTransactions
#10, 142
#10, 76
#10, 77
#10, 80
#10, 71
#10, 65
#10, 72
#10, 93
#10, 74
#10, 61
#10, 93
#10, 112
#10, 92
#10, 61
#10, 82
#10, 95
#10, 143
#10, 116
#10, 120
#10, 78
#10, 83
#10, 73
#10, 78
10, 91
10, 80
10, 59
10, 72
10, 84
10, 65
10, 58
